
package com.afshin.Webservice.stub.productline;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductlineInt", targetNamespace = "http://Webservice.afshin.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductlineInt {


    /**
     * 
     * @return
     *     returns com.afshin.Webservice.stub.productline.ProductlineArray
     */
    @WebMethod
    @WebResult(name = "Productlines", partName = "Productlines")
    @Action(input = "http://Webservice.afshin.com/ProductlineInt/allRequest", output = "http://Webservice.afshin.com/ProductlineInt/allResponse")
    public ProductlineArray all();

    /**
     * 
     * @param productline
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.afshin.com/ProductlineInt/updateRequest", output = "http://Webservice.afshin.com/ProductlineInt/updateResponse")
    public String update(
        @WebParam(name = "Productline", partName = "Productline")
        Productline productline);

    /**
     * 
     * @param productlineNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.afshin.com/ProductlineInt/deleteRequest", output = "http://Webservice.afshin.com/ProductlineInt/deleteResponse")
    public String delete(
        @WebParam(name = "ProductlineNumber", partName = "ProductlineNumber")
        String productlineNumber);

    /**
     * 
     * @param productline
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.afshin.com/ProductlineInt/insertRequest", output = "http://Webservice.afshin.com/ProductlineInt/insertResponse")
    public String insert(
        @WebParam(name = "Productline", partName = "Productline")
        Productline productline);

    /**
     * 
     * @param productlineNumber
     * @return
     *     returns com.afshin.Webservice.stub.productline.Productline
     */
    @WebMethod
    @WebResult(name = "Productline", partName = "Productline")
    @Action(input = "http://Webservice.afshin.com/ProductlineInt/findRequest", output = "http://Webservice.afshin.com/ProductlineInt/findResponse")
    public Productline find(
        @WebParam(name = "ProductlineNumber", partName = "ProductlineNumber")
        String productlineNumber);

}
