
package com.afshin.Webservice.stub.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderInt", targetNamespace = "http://Webservice.afshin.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderInt {


    /**
     * 
     * @return
     *     returns com.afshin.Webservice.stub.order.OrderArray
     */
    @WebMethod
    @WebResult(name = "Orders", partName = "Orders")
    @Action(input = "http://Webservice.afshin.com/OrderInt/allRequest", output = "http://Webservice.afshin.com/OrderInt/allResponse")
    public OrderArray all();

    /**
     * 
     * @param order
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.afshin.com/OrderInt/updateRequest", output = "http://Webservice.afshin.com/OrderInt/updateResponse")
    public String update(
        @WebParam(name = "Order", partName = "Order")
        Order order);

    /**
     * 
     * @param orderNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.afshin.com/OrderInt/deleteRequest", output = "http://Webservice.afshin.com/OrderInt/deleteResponse")
    public String delete(
        @WebParam(name = "orderNumber", partName = "orderNumber")
        int orderNumber);

    /**
     * 
     * @param order
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.afshin.com/OrderInt/insertRequest", output = "http://Webservice.afshin.com/OrderInt/insertResponse")
    public String insert(
        @WebParam(name = "Order", partName = "Order")
        Order order);

    /**
     * 
     * @param orderNumber
     * @return
     *     returns com.afshin.Webservice.stub.order.Order
     */
    @WebMethod
    @WebResult(name = "Order", partName = "Order")
    @Action(input = "http://Webservice.afshin.com/OrderInt/findRequest", output = "http://Webservice.afshin.com/OrderInt/findResponse")
    public Order find(
        @WebParam(name = "orderNumber", partName = "orderNumber")
        int orderNumber);

}
