
package com.afshin.Webservice.stub.orderdetail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderdetailInt", targetNamespace = "http://Webservice.afshin.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderdetailInt {


    /**
     * 
     * @return
     *     returns com.afshin.Webservice.stub.orderdetail.OrderdetailArray
     */
    @WebMethod
    @WebResult(name = "OrderdetailList", partName = "OrderdetailList")
    @Action(input = "http://Webservice.afshin.com/OrderdetailInt/allRequest", output = "http://Webservice.afshin.com/OrderdetailInt/allResponse")
    public OrderdetailArray all();

    /**
     * 
     * @param orderdetail
     * @return
     *     returns com.afshin.Webservice.stub.orderdetail.OrderdetailPK
     */
    @WebMethod
    @WebResult(name = "OrderdetailPK", partName = "OrderdetailPK")
    @Action(input = "http://Webservice.afshin.com/OrderdetailInt/updateRequest", output = "http://Webservice.afshin.com/OrderdetailInt/updateResponse")
    public OrderdetailPK update(
        @WebParam(name = "Orderdetail", partName = "Orderdetail")
        Orderdetail orderdetail);

    /**
     * 
     * @param orderNumber
     * @param productCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.afshin.com/OrderdetailInt/deleteRequest", output = "http://Webservice.afshin.com/OrderdetailInt/deleteResponse")
    public String delete(
        @WebParam(name = "OrderNumber", partName = "OrderNumber")
        int orderNumber,
        @WebParam(name = "ProductCode", partName = "ProductCode")
        String productCode);

    /**
     * 
     * @param orderdetail
     * @return
     *     returns com.afshin.Webservice.stub.orderdetail.OrderdetailPK
     */
    @WebMethod
    @WebResult(name = "OrderdetailPK", partName = "OrderdetailPK")
    @Action(input = "http://Webservice.afshin.com/OrderdetailInt/insertRequest", output = "http://Webservice.afshin.com/OrderdetailInt/insertResponse")
    public OrderdetailPK insert(
        @WebParam(name = "Orderdetail", partName = "Orderdetail")
        Orderdetail orderdetail);

    /**
     * 
     * @param orderNumber
     * @param productCode
     * @return
     *     returns com.afshin.Webservice.stub.orderdetail.Orderdetail
     */
    @WebMethod
    @WebResult(name = "Orderdetail", partName = "Orderdetail")
    @Action(input = "http://Webservice.afshin.com/OrderdetailInt/findRequest", output = "http://Webservice.afshin.com/OrderdetailInt/findResponse")
    public Orderdetail find(
        @WebParam(name = "OrderNumber", partName = "OrderNumber")
        int orderNumber,
        @WebParam(name = "ProductCode", partName = "ProductCode")
        String productCode);

}
